# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googlemock/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googlemock/cmake/gmock.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googlemock/cmake/gmock_main.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googletest/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googletest/cmake/Config.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googletest/cmake/gtest.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googletest/cmake/gtest_main.pc.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/CLionProjects/C++Basics1/test-framework/googletest-src/googletest/cmake/internal_utils.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/BasicConfigVersion-AnyNewerVersion.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/CMakeDependentOption.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/FindPythonInterp.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/GNUInstallDirs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/Internal/CheckSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/share/cmake-3.24/Modules/WriteBasicConfigVersionFile.cmake))

/Users/said/CLionProjects/C++Basics1/cmake-build-release/CMakeFiles/cmake.check_cache: $(TARGETS)
	/Users/said/Library/Application\ Support/JetBrains/Toolbox/apps/CLion/ch-0/223.8617.54/CLion.app/Contents/bin/cmake/mac/bin/cmake -H/Users/said/CLionProjects/C++Basics1 -B/Users/said/CLionProjects/C++Basics1/cmake-build-release
